In [1]:
import pandas as pd
df = pd.read_csv("data/unemployed_complete.csv",sep=",")

In [4]:
df

,Year,Month,District Code,District Name,Neighborhood Code,Neighborhood Name,Gender,Demand_occupation,Number
0,2021,January,1,Ciutat Vella,1,el Raval,Female,Registered unemployed,2139
1,2021,January,1,Ciutat Vella,2,el Barri Gòtic,Female,Registered unemployed,673
2,2021,January,1,Ciutat Vella,3,la Barceloneta,Female,Registered unemployed,722
3,2021,January,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Female,Registered unemployed,995
4,2021,January,2,Eixample,5,el Fort Pienc,Female,Registered unemployed,896
...,...,...,...,...,...,...,...,...,...
23083,2013,December,10,Sant Martí,70,el Besòs i el Maresme,Female,Registered unemployed,1043
23084,2013,December,10,Sant Martí,71,Provençals del Poblenou,Female,Registered unemployed,738
23085,2013,December,10,Sant Martí,72,Sant Martí de Provençals,Female,Registered unemployed,1015
23086,2013,December,10,Sant Martí,73,la Verneda i la Pau,Female,Registered unemployed,1145
23087,2013,December,99,No consta,99,No consta,Female,Registered unemployed,0

In [5]:
df = df[df["Demand_occupation"]=="Registered unemployed"]

In [12]:
df = df[df["Number"]!=0]
df

,Year,Month,District Code,District Name,Neighborhood Code,Neighborhood Name,Gender,Demand_occupation,Number
0,2021,January,1,Ciutat Vella,1,el Raval,Female,Registered unemployed,2139
1,2021,January,1,Ciutat Vella,2,el Barri Gòtic,Female,Registered unemployed,673
2,2021,January,1,Ciutat Vella,3,la Barceloneta,Female,Registered unemployed,722
3,2021,January,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Female,Registered unemployed,995
4,2021,January,2,Eixample,5,el Fort Pienc,Female,Registered unemployed,896
...,...,...,...,...,...,...,...,...,...
23082,2013,December,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,Female,Registered unemployed,458
23083,2013,December,10,Sant Martí,70,el Besòs i el Maresme,Female,Registered unemployed,1043
23084,2013,December,10,Sant Martí,71,Provençals del Poblenou,Female,Registered unemployed,738
23085,2013,December,10,Sant Martí,72,Sant Martí de Provençals,Female,Registered unemployed,1015
23086,2013,December,10,Sant Martí,73,la Verneda i la Pau,Female,Registered unemployed,1145

In [14]:
df.columns = ['Year', 'Month', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Gender', 'Demand_occupation', 'Number']

In [15]:
df.to_csv("data/unemployed_complete.csv",index=False)