In [2]:
import pandas as pd
df = pd.read_csv("unemployed_complete.csv",sep=",")

In [4]:
df["District.Name"].unique()

array(['Ciutat Vella', 'Eixample', 'Sants-Montjuïc', 'Les Corts',
       'Sarrià-Sant Gervasi', 'Gràcia', 'Horta-Guinardó', 'Nou Barris',
       'Sant Andreu', 'Sant Martí', 'No consta'], dtype=object)

In [7]:
df = df[df["District.Name"]!="No consta"]

In [8]:
df

,Year,Month,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Demand_occupation,Total
0,2021,January,1,Ciutat Vella,1,el Raval,Female,Registered unemployed,2139
1,2021,January,1,Ciutat Vella,2,el Barri Gòtic,Female,Registered unemployed,673
2,2021,January,1,Ciutat Vella,3,la Barceloneta,Female,Registered unemployed,722
3,2021,January,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Female,Registered unemployed,995
4,2021,January,2,Eixample,5,el Fort Pienc,Female,Registered unemployed,896
...,...,...,...,...,...,...,...,...,...
15074,2013,December,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,Female,Registered unemployed,458
15075,2013,December,10,Sant Martí,70,el Besòs i el Maresme,Female,Registered unemployed,1043
15076,2013,December,10,Sant Martí,71,Provençals del Poblenou,Female,Registered unemployed,738
15077,2013,December,10,Sant Martí,72,Sant Martí de Provençals,Female,Registered unemployed,1015
15078,2013,December,10,Sant Martí,73,la Verneda i la Pau,Female,Registered unemployed,1145

In [9]:
df.to_csv("unemployed_complete.csv",index=False)